[
    {
        "id": 1,
        "subscriberNIC": "993201774V",
        "firstName": "Stelin",
        "lastName": "Dinoshan",
        "password": "123456",
        "primaryPhone": 770770770,
        "secondaryPhone": 771234567,
        "email": "dinoshan@gmail.com",
        "ppVerified": "1",
        "branchID": 3,
        "areaCode": 3,
        "roadID": 4,
        "customerID": 5,
        "connectionAddress": "KFC",
        "connectionID": "1",
        "oldID": "398",
        "connectionLocation": "KFC",
        "status": "CANCEL",
        "connectedDate": "2022-11-02",
        "connectionStatus": "DEACTIVE",
        "connectionType": "normal",
        "tvCount": "1",
        "remarks": null,
        "dueAmount": null,
        "actionDate": "2022-11-02T00:00:00.000Z"
    },
    {
        "id": 2,
        "subscriberNIC": "993201774V",
        "firstName": "Stelin",
        "lastName": "Dinoshan",
        "password": "123456",
        "primaryPhone": 770770770,
        "secondaryPhone": 771234567,
        "email": "dinoshan@gmail.com",
        "ppVerified": "1",
        "branchID": 3,
        "areaCode": 3,
        "roadID": 4,
        "customerID": 5,
        "connectionAddress": "KFC",
        "connectionID": "1",
        "oldID": "398",
        "connectionLocation": "KFC",
        "status": "CANCEL",
        "connectedDate": "2022-11-02",
        "connectionStatus": "DEACTIVE",
        "connectionType": "normal",
        "tvCount": "1",
        "remarks": null,
        "dueAmount": null,
        "actionDate": "2022-11-02T00:00:00.000Z"
    },
    {
        "id": 3,
        "subscriberNIC": "993201774V",
        "firstName": "Stelin",
        "lastName": "Dinoshan",
        "password": "123456",
        "primaryPhone": 770770770,
        "secondaryPhone": 771234567,
        "email": "dinoshan@gmail.com",
        "ppVerified": "1",
        "branchID": 3,
        "areaCode": 3,
        "roadID": 4,
        "customerID": 5,
        "connectionAddress": "KFC",
        "connectionID": "1",
        "oldID": "398",
        "connectionLocation": "KFC",
        "status": "CANCEL",
        "connectedDate": "2022-11-02",
        "connectionStatus": "DEACTIVE",
        "connectionType": "normal",
        "tvCount": "1",
        "remarks": null,
        "dueAmount": null,
        "actionDate": "2022-11-02T00:00:00.000Z"
    },
    {
        "id": 4,
        "subscriberNIC": "993201774V",
        "firstName": "Stelin",
        "lastName": "Dinoshan",
        "password": "123456",
        "primaryPhone": 770770770,
        "secondaryPhone": 771234567,
        "email": "dinoshan@gmail.com",
        "ppVerified": "1",
        "branchID": 3,
        "areaCode": 3,
        "roadID": 4,
        "customerID": 5,
        "connectionAddress": "KFC",
        "connectionID": "1",
        "oldID": "398",
        "connectionLocation": "SLIIT",
        "status": "Active",
        "connectedDate": "2022-11-02",
        "connectionStatus": "ACTIVE",
        "connectionType": "normal",
        "tvCount": "02",
        "remarks": null,
        "dueAmount": 5000,
        "actionDate": "2022-11-02T00:00:00.000Z"
    },
    {
        "id": 5,
        "subscriberNIC": "993201774V",
        "firstName": "Stelin",
        "lastName": "Dinoshan",
        "password": "123456",
        "primaryPhone": 770770770,
        "secondaryPhone": 771234567,
        "email": "dinoshan@gmail.com",
        "ppVerified": "1",
        "branchID": 3,
        "areaCode": 3,
        "roadID": 4,
        "customerID": 1,
        "connectionAddress": "KFC",
        "connectionID": "CON001",
        "oldID": "398",
        "connectionLocation": "SLIIT",
        "status": "Active",
        "connectedDate": "2022-11-02",
        "connectionStatus": "ACTIVE",
        "connectionType": "normal",
        "tvCount": "02",
        "remarks": null,
        "dueAmount": 5000,
        "actionDate": "2022-11-02T00:00:00.000Z"
    },
    {
        "id": 6,
        "subscriberNIC": "993201774V",
        "firstName": "Stelin",
        "lastName": "Dinoshan",
        "password": "123456",
        "primaryPhone": 770770770,
        "secondaryPhone": 771234567,
        "email": "dinoshan@gmail.com",
        "ppVerified": "1",
        "branchID": 3,
        "areaCode": 3,
        "roadID": 4,
        "customerID": 2,
        "connectionAddress": "KFC",
        "connectionID": "CON002",
        "oldID": "398",
        "connectionLocation": "Jaffna",
        "status": "Active",
        "connectedDate": "2022-11-02",
        "connectionStatus": "ACTIVE",
        "connectionType": "normal",
        "tvCount": "02",
        "remarks": null,
        "dueAmount": 5000,
        "actionDate": "2022-11-02T00:00:00.000Z"
    },
    {
        "id": 7,
        "subscriberNIC": "993201774V",
        "firstName": "Stelin",
        "lastName": "Dinoshan",
        "password": "123456",
        "primaryPhone": 770770770,
        "secondaryPhone": 771234567,
        "email": "dinoshan@gmail.com",
        "ppVerified": "1",
        "branchID": 3,
        "areaCode": 3,
        "roadID": 4,
        "customerID": 2,
        "connectionAddress": "KFC",
        "connectionID": "CON003",
        "oldID": "398",
        "connectionLocation": "Colombo",
        "status": "Active",
        "connectedDate": "2022-11-02",
        "connectionStatus": "ACTIVE",
        "connectionType": "normal",
        "tvCount": "03",
        "remarks": null,
        "dueAmount": 5000,
        "actionDate": "2022-11-02T00:00:00.000Z"
    },
    {
        "id": 8,
        "subscriberNIC": "993201774V",
        "firstName": "Stelin",
        "lastName": "Dinoshan",
        "password": "123456",
        "primaryPhone": 770770770,
        "secondaryPhone": 771234567,
        "email": "dinoshan@gmail.com",
        "ppVerified": "1",
        "branchID": 3,
        "areaCode": 3,
        "roadID": 4,
        "customerID": 4,
        "connectionAddress": "KFC",
        "connectionID": "CON004",
        "oldID": "398",
        "connectionLocation": "Colombo",
        "status": "Active",
        "connectedDate": "2022-11-02",
        "connectionStatus": "ACTIVE",
        "connectionType": "normal",
        "tvCount": "03",
        "remarks": null,
        "dueAmount": 5000,
        "actionDate": "2022-11-02T00:00:00.000Z"
    },
    {
        "id": 9,
        "subscriberNIC": "993201774V",
        "firstName": "Stelin",
        "lastName": "Dinoshan",
        "password": "123456",
        "primaryPhone": 770770770,
        "secondaryPhone": 771234567,
        "email": "dinoshan@gmail.com",
        "ppVerified": "1",
        "branchID": 3,
        "areaCode": 3,
        "roadID": 4,
        "customerID": 5,
        "connectionAddress": "KFC",
        "connectionID": "CON005",
        "oldID": "398",
        "connectionLocation": "Wellawata",
        "status": "Active",
        "connectedDate": "2022-11-02",
        "connectionStatus": "ACTIVE",
        "connectionType": "normal",
        "tvCount": "03",
        "remarks": null,
        "dueAmount": 5000,
        "actionDate": "2022-11-02T00:00:00.000Z"
    }
]
var demoroad = [
    {
        "id": 1,
        "areaID": 3,
        "road": "Marine Drive"
    },
    {
        "id": 2,
        "areaID": 3,
        "road": "Marine Drive"
    },
    {
        "id": 3,
        "areaID": 3,
        "road": "Marine Drive"
    },
    {
        "id": 4,
        "areaID": 3,
        "road": "Marine Drive"
    },
    {
        "id": 5,
        "areaID": 3,
        "road": "Marine Drive"
    },
    {
        "id": 6,
        "areaID": 3,
        "road": "Marine Drive"
    },
    {
        "id": 7,
        "areaID": 3,
        "road": "Marine Drive"
    }
]

export interface TicketElement {
    "id": number,
    "connectionID": number, "ticketID": string,
    "createdBy": string, "assignedTo": string,
    "assignedToID": string, "updatedBy": string,
    "subject": string, "description": string,
    "reason": string, "phone": string,
    "status": string, "createdAt": string,
    "updatedAt": string, "closedAt": string
  }
  ['ticketID','connectionID','description',
  'phone','createdBy','createdAt'];